REPO_PATH: '.'
VENV_PATH: ''
VENV_DIR: ''
TEST_COMMAND: ''
AIDER_PATH: ''
MAX_LINE_LENGTH: 100
AUTOPEP8_FIX: false
AIDER_MODEL: 'openrouter/anthropic/claude-3.5-sonnet:beta'
AIDER_WEAK_MODEL: 'openrouter/anthropic/claude-3-haiku-20240307'
LINTER: 'pylint'
LINE_COUNT_MAX: 200
LINE_COUNT_MIN: 10
ENABLE_BLACK: false
# Security settings
MAX_CODE_LENGTH: 50000
MAX_QUESTION_LENGTH: 1000
MAX_REQUEST_SIZE_MB: 1
MAX_MEMORY_MB: 1000
API_RATE_LIMIT: 5

# Language settings
SUPPORTED_LANGUAGES:
  - python
  - javascript
  - java
  - cpp
  - csharp
  - go
  - rust
  - typescript
  - ruby
  - php

LANGUAGE_MAX_LENGTHS:
  default: 50000
  python: 50000
  javascript: 50000
  java: 100000
  cpp: 50000
  csharp: 75000
  go: 50000
  rust: 50000
  typescript: 50000
  ruby: 50000
  php: 50000

DANGEROUS_PATTERNS:
  default:
    - "rm -rf /"  # More specific to root deletion
    - "mkfs."     # More specific to filesystem formatting
    - "dd if=/dev/"
    - "wget http"  # More specific to downloading
    - "curl http"  # More specific to downloading
    - "> /dev/sd"  # More specific to device writing
    - "> /proc/sys"
    - "> /sys/"
    - "sudo rm"
    - "chmod 777"  # Specific dangerous permission
    - "chown -R"  # Recursive ownership change
  python:
    - "os.system("
    - "subprocess.call("
    - "subprocess.run("
    - "eval(input"
    - "exec(input"
    - "__import__('os')"
  javascript:
    - "eval(input"
    - "new Function("
    - "process.exit("
    - "require('child_process')."
  java:
    - "Runtime.getRuntime().exec("
    - "ProcessBuilder("
    - "System.exit(0)"  # Only block explicit exits
