REPO_PATH: '/app'
VENV_PATH: ''
VENV_DIR: ''
TEST_COMMAND: ''
AIDER_PATH: ''
MAX_LINE_LENGTH: 100
AUTOPEP8_FIX: false
LINTER: 'pylint'
LINE_COUNT_MAX: 500
LINE_COUNT_MIN: 10
ENABLE_BLACK: false
# Security settings
MAX_CODE_LENGTH: 50000
MAX_QUESTION_LENGTH: 1000
MAX_REQUEST_SIZE_MB: 1
MAX_MEMORY_MB: 1000
API_RATE_LIMIT: 5
AIDER_MODEL: 'codestral/codestral-latest'
AIDER_WEAK_MODEL: 'codestral/codestral-latest'