REPO_PATH: '.'
VENV_PATH: ''
VENV_DIR: ''
TEST_COMMAND: ''
AIDER_PATH: ''
MAX_LINE_LENGTH: 100
AUTOPEP8_FIX: false
AIDER_MODEL: 'openrouter/anthropic/claude-3.5-sonnet:beta'
AIDER_WEAK_MODEL: 'openrouter/anthropic/claude-3-haiku-20240307'
LINTER: 'pylint'
LINE_COUNT_MAX: 200
LINE_COUNT_MIN: 10
ENABLE_BLACK: false
# Security settings
MAX_CODE_LENGTH: 50000
MAX_QUESTION_LENGTH: 1000
MAX_REQUEST_SIZE_MB: 1
