REPO_PATH: "/full/path/to/repo"
LINTER: "pylint"  # Options: "pylint", "flake8", "ruff"
VENV_PATH: "/full/path/to/repo/<virtual env dir>"
# venv .venv etc.
VENV_DIR: "venv"
TEST_COMMAND: ["python", "-m", "pytest", "-q"]
AIDER_PATH: "/full/path/to/aider"
MAX_LINE_LENGTH: 100
AUTOPEP8_FIX: True
ENABLE_BLACK: False
# the model in this early release is a full path, shortcut options have not been tested
AIDER_MODEL: "<model you want to use>"
AIDER_WEAK_MODEL: "<weak model you want to use>"
LINE_COUNT_MAX: 500
LINE_COUNT_MIN: 50
