    version: '3'
    services:
      app:
        build: .
        environment:
          - ANTHROPIC_API_KEY={$ANTHROPIC_API_KEY}
          - OPENROUTER_API_KEY={$OPENROUTER_API_KEY}
          - OPENAI_API_KEY={$OPEN_API_KEY}
